# Generated by Django 5.1.3 on 2024-11-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='p_email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
