# Generated by Django 5.1.3 on 2024-11-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_booking_p_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
